services:
  proxy:
    build: ../
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    restart: unless-stopped
    command: [ "kamal-proxy", "run", "--debug", "--metrics-port=9000" ]

  web:
    build: ./upstream
    deploy:
      replicas: 4
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
