#! /usr/bin/env bash

set -e

usage() {
  echo "Usage: $0 <version>"
  echo "  <version>    The new version number (e.g. 1.2.3)"
  exit 1
}

if [ $# -ne 1 ]; then
  usage
fi

VERSION=$1
TAG=v$VERSION

make test
git fetch origin --tags

git tag -a ${TAG} -m "Version ${VERSION}

- list important changes here" -e

docker build \
  --platform linux/amd64,linux/arm64 \
  -t ${DOCKER_HOST_}/anycpu/kamal-proxy:${VERSION} \
  -t ${DOCKER_HOST_}/anycpu/kamal-proxy:latest \
  --label "org.opencontainers.image.title=kamal-proxy" \
  -f Dockerfile_alpine .

docker login --username $DOCKER_USER --password $DOCKER_PASSWORD $DOCKER_HOST_

docker push ${DOCKER_HOST_}/anycpu/kamal-proxy:${VERSION}
docker push ${DOCKER_HOST_}/anycpu/kamal-proxy:latest

git push origin tag ${TAG}
